### PR TITLE
Upgrade esprima to 2.4.0

### PR DESCRIPTION
**Pull request by akiellor**

### CODE REVIEW

**Comment by akiellor** [comment]
Is there any feedback for this PR?

Happy to make any required changes.

**Comment by akiellor** [comment]
Would be nice to get some client builds off my personal branch of jsfmt. This is also a fix for the current broken master. Any eta for a code review?

**Comment by terinjokes** [comment]
Ditto, I'll like to get company builds off my branch.

**Comment by r4j4h** [comment]
+1 Merging this in would allow the other issues to be closed too :)

**Comment by akiellor** [comment]
@brettlangdon any chance to get a look at this?

**Comment by brettlangdon** [comment]
These changes look alright to me, however there are some changes to the styleguide, not sure if they are caused by these changes or the styleguide not being updated with previous changes.

However... I am content with the changes that it is making. Please update the style guide in this PR.

```diff
diff --git a/examples/styleGuide.js b/examples/styleGuide.js
index a466c58..5a10605 100644
--- a/examples/styleGuide.js
+++ b/examples/styleGuide.js
@@ -9,7 +9,9 @@
     3
   ];
 
-  var a, b, c;
+  var a;
+  var b;
+  var c;
   var another = test;
 
   var sum = 0;
@@ -78,13 +80,13 @@
   }
 
   var str = '<span>' + fun([
-    1, 2, 3
-  ]) + '</span>';
+      1, 2, 3
+    ]) + '</span>';
 
   // TODO: Keep indentation of BinaryOperators inside function call args
   $(document.body).append('<li>' +
-  myVar.toString() +
-  '</li>');
+    myVar.toString() +
+    '</li>');
 
   var myVar = new myVarTypes[
     'A type']();
@@ -106,7 +108,7 @@
 
   var nestedObjects = [{
     a: true
-    }, {
+  }, {
     a: false
   }];
```


As a side note, I do not have contributor rights, so I cannot merge pull requests. But :+1: from me once the styleguide gets updated.

**Comment by terinjokes** [comment]
@brettlangdon the seperate "var" lines were changed as a result of #125 and the bracket changes were an upstream esformatter fix that was "merged" and in jsfmt for a while now. The two remaining changes look similar, and probably changed as a result of an esformatter patch.

**Comment by brettlangdon** [comment]
@terinjokes :+1: thanks

**Comment by akiellor** [comment]
@brettlangdon Thanks for the update!

I just ran `grunt fmt` and committed the result.

**Comment by akiellor** [comment]
@brettlangdon who does have contributor rights? Could we link them in to have a look?

**Comment by brettlangdon** [comment]
@akiellor no clue, @jimfleming might know who can help out.

**Comment by akiellor** [comment]
@jimfleming any comments on this?

**Comment by dschleef** [comment]
I'll make sure this is reviewed soon.

**Comment by jimfleming** [comment]
Looking at this now.

**Comment by jimfleming** [comment]
Changes look good. Tests pass locally and overall seems to work correctly.

Also, repo permissions have been worked out so I can merge this and @brettlangdon is now a maintainer as well so more than one person can merge PRs going forward.

**Comment by akiellor** [comment]
Thanks so much!

**Comment by terinjokes** [comment]
Likewise, thanks for getting it sorted out!

**Pull request merged**
