### PR TITLE
Revert "Update deep-extend and escodegen"

### PR DESCRIPTION
**Pull request by jimfleming**
Reverts rdio/jsfmt#139

Looks like it broke some tests. The CI bot didn't report anything which is my bad.

### CODE REVIEW

**Comment by brettlangdon** [comment]
hmm... that sucks, everything was passing for me before, but I'll take a
look.

**Comment by jimfleming** [comment]
Weird, the revert seems to be failing too.

**Comment by brettlangdon** [comment]
hmm, seems like the upgrade of esformatter caused the issue. looks like it has weird indenting for comment in the try/catch block.

**Comment by brettlangdon** [comment]
open issue: https://github.com/millermedeiros/rocambole/issues/26

**Comment by millermedeiros** [comment]
esformatter@0.5.1 should fix the try/catch issue - I also just released rocambole@0.5.1 to avoid the problem.

**Comment by jimfleming** [comment]
Going to start over on this.

**Pull request closed without merging**
